AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS Patronus Micro Services

Resources:
  ProductResource:
    Type: AWS::Serverless::Function
    Properties:
      Handler: product.handler
      Runtime: nodejs4.3
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /product/{SKU}
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /product
            Method: post
        PutEvent:
          Type: Api
          Properties:
            Path: /product
            Method: put

  OrderResource:
      Type: AWS::Serverless::Function
      Properties:
        Handler: order.handler
        Runtime: nodejs4.3
        Role:
          Fn::ImportValue:
            !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
        Events:
          GetEvent:
            Type: Api
            Properties:
              Path: /order
              Method: get
          PostEvent:
            Type: Api
            Properties:
              Path: /order
              Method: post
          PutEvent:
            Type: Api
            Properties:
              Path: /order
              Method: put